name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        env:
          FIREBASE_SERVICE_ACCOUNT_NAMEAGE_EC0A2: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_NAMEAGE_EC0A2 }}  # GitHub Secrets에서 서비스 계정 키 가져오기
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NAMEAGE_EC0A2 }}'
          channelId: live
          projectId: nameage-ec0a2
